# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data Against COVID-19 / FR
description: Initiative Data Against COVID-19 / FR
baseurl:  # the subpath of your site, e.g. /support
url: https://opencovid19-fr.github.io # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title

content_type: Data Against COVID-19 / FR #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Data Against COVID-19 / FR
header: Data Against COVID-19 / FR
subheader: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

meta_image: odin-meta.png

# Social Links
twitter_username: opencovid19
facebook_page: 
github_username: opencovid19-fr
email: 
linkedin_page:
instagram_username: 


# Navivation
nav_item_one: Github
nav_item_one_link: https://github.com/opencovid19-fr

nav_item_two: Twitter
nav_item_two_link: https://twitter.com/opencovid19

nav_item_three: #
nav_item_three_link: #

nav_button: Return to Home
nav_button_link: https://opencovid19-fr.github.io

# More Help
help_one_title: Data Against COVID-19 / FR Bugs
help_one_content: If you find any bugs or problems, please open an issue over on Github.
help_one_button: Github
help_one_link: https://github.com/opencovid19-fr

help_two_title: Twitter
help_two_content: Feel free to tweet us your suggestions.
help_two_button: Twitter
help_two_link: https://twitter.com/opencovid19

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
